name: Build
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to release'
        required: false

jobs:
  build:
    runs-on: macos-13
    name: Build macOS x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm 8
        run: npm install -g pnpm@8.15.9

      - name: Determine Version
        shell: bash
        run: |
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION=$(jq -r '.version' package.json)

          if [ "${{ github.event.inputs.version }}" == "" ]; then
            BASE_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
            RELEASE_VERSION="${BASE_VERSION}-beta-${GIT_COMMIT_HASH}"
          else
            INPUT_VERSION="${{ github.event.inputs.version }}"
            CLEAN_VERSION=$(echo "$INPUT_VERSION" | sed 's/^v//')
            RELEASE_VERSION="$CLEAN_VERSION"
          fi

          jq --arg version "$RELEASE_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json

      - name: Install Dependencies
        env:
          npm_config_arch: x64
          npm_config_target_arch: x64
        run: |
          SKIP_PREPARE=1 pnpm install --no-frozen-lockfile
          pnpm prepare --x64

      - name: Build
        env:
          npm_config_arch: x64
          npm_config_target_arch: x64
        run: pnpm build:mac --x64

      - name: Generate latest.yml
        run: SKIP_CHANGELOG=1 pnpm updater

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64
          path: |
            dist/[Kk]oala?[Cc]lash*
            !dist/*.plist
            !dist/*blockmap*
            latest.yml
            changelog.md

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true

      - name: Delete current pre-release assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: pre-release
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release
          body_path: bin/changelog.md
          files: |
            bin/latest.yml
            bin/[Kk]oala?[Cc]lash*
          prerelease: true
